version: "3.8"

# Docker Compose para monitoreo con Prometheus y Grafana
services:
  # Servicios principales (extendidos de docker-compose.yml)
  rt:
    extends:
      file: docker-compose.yml
      service: rt
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=3002"
      - "prometheus.path=/metrics"

  db:
    extends:
      file: docker-compose.yml
      service: db
    labels:
      - "prometheus.enable=true"
      - "prometheus.port=3306"

  # Prometheus para métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: rt-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    networks:
      - rt-network
      - monitoring

  # Grafana para visualización
  grafana:
    image: grafana/grafana:latest
    container_name: rt-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    networks:
      - monitoring

  # Node Exporter para métricas del sistema
  node-exporter:
    image: prom/node-exporter:latest
    container_name: rt-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - monitoring

  # MySQL Exporter para métricas de base de datos
  mysql-exporter:
    image: prom/mysqld-exporter:latest
    container_name: rt-mysql-exporter
    restart: unless-stopped
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME=root:root_password@(db:3306)/
    depends_on:
      - db
    networks:
      - rt-network
      - monitoring

  # Apache Exporter para métricas de Apache
  apache-exporter:
    image: lusotycoon/apache-exporter:latest
    container_name: rt-apache-exporter
    restart: unless-stopped
    ports:
      - "9117:9117"
    command:
      - "--scrape_uri=http://rt:3002/server-status/?auto"
    depends_on:
      - rt
    networks:
      - rt-network
      - monitoring

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring:
    driver: bridge
