version: "3.8"

services:
  rt:
    build: .
    container_name: request-tracker
    restart: always
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      RT_DATABASE_HOST: db
      RT_DATABASE_NAME: rt4
      RT_DATABASE_USER: rt_user
      RT_DATABASE_PASSWORD: rt_pass
      RT_ROOT_PASSWORD: root_password
    volumes:
      - rt-data:/opt/rt6/var

  db:
    image: mariadb:11.3
    container_name: rt-db
    restart: always
    environment:
      MYSQL_DATABASE: rt4
      MYSQL_USER: rt_user
      MYSQL_PASSWORD: rt_pass
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ROOT_HOST: "%" # Permitir acceso root desde cualquier host
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql

volumes:
  rt-data:
  db-data:
