version: "3.8"

# Docker Compose para desarrollo con hot-reload y debugging
services:
  rt-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: request-tracker-dev
    restart: unless-stopped
    depends_on:
      db-dev:
        condition: service_healthy
    ports:
      - "3001:3002"
      - "3003:3003" # Puerto adicional para desarrollo
    environment:
      RT_DATABASE_HOST: db-dev
      RT_DATABASE_NAME: rt6_dev
      RT_DATABASE_USER: rt_user
      RT_DATABASE_PASSWORD: rt_pass_dev
      RT_ROOT_PASSWORD: root_password_dev
      RT_ORGANIZATION: dev.example.com
      RT_CORRESPOND_ADDRESS: rt-dev@example.com
      RT_TIMEZONE: UTC
      # Configuración de desarrollo
      RT_LOG_LEVEL: debug
      PERL_DL_NONLAZY: 1
    volumes:
      - rt-data-dev:/opt/rt6/var
      - rt-logs-dev:/var/log/apache2
      - ./RT_SiteConfig.pm:/opt/rt6/etc/RT_SiteConfig.pm:ro
      - ./rt-apache.conf:/etc/apache2/sites-available/rt.conf:ro
    networks:
      - rt-network-dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db-dev:
    image: mysql:8.0
    container_name: rt-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: rt6_dev
      MYSQL_USER: rt_user
      MYSQL_PASSWORD: rt_pass_dev
      MYSQL_ROOT_PASSWORD: root_password_dev
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=128M
      - --max-connections=100
      - --general-log=1
      - --general-log-file=/var/log/mysql/general.log
      - --slow-query-log=1
      - --slow-query-log-file=/var/log/mysql/slow.log
      - --long-query-time=1
    volumes:
      - db-data-dev:/var/lib/mysql
      - db-logs-dev:/var/log/mysql
    ports:
      - "3306:3306" # Exponer puerto MySQL para desarrollo
    networks:
      - rt-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Opcional: PhpMyAdmin para desarrollo de base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rt-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db-dev
    environment:
      PMA_HOST: db-dev
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password_dev
    ports:
      - "8080:80"
    networks:
      - rt-network-dev

volumes:
  rt-data-dev:
    driver: local
  db-data-dev:
    driver: local
  rt-logs-dev:
    driver: local
  db-logs-dev:
    driver: local

networks:
  rt-network-dev:
    driver: bridge
