version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: rt-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rt_root_password
      MYSQL_DATABASE: rt6
      MYSQL_USER: rt_user
      MYSQL_PASSWORD: rt_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - rt-network

  rt:
    build: .
    container_name: rt-app
    restart: unless-stopped
    environment:
      - RT_DATABASE_HOST=mysql
      - RT_DATABASE_NAME=rt6
      - RT_DATABASE_USER=rt_user
      - RT_DATABASE_PASSWORD=rt_password
      - RT_WEB_DOMAIN=localhost
      - RT_WEB_PORT=80
    volumes:
      - rt_data:/opt/rt6/var
      - ./config:/opt/rt6/etc/RT_SiteConfig.d
      - ./plugins:/opt/rt6/local/plugins
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - rt-network

volumes:
  mysql_data:
  rt_data:

networks:
  rt-network:
    driver: bridge
